name: PHPCS

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.MD'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.MD'


jobs:
  phpcs:
    name: Run PHPCS (WPCS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Show PHPCS/Standards versions
        run: |
          vendor/bin/phpcs -i || true
          vendor/bin/phpcs --version

      - name: Run PHPCS
        run: vendor/bin/phpcs -q
